blank_issues_enabled: false

# TODO: Redirect support questions
# contact_links:
#   - name: ❓ Question
#     url: https://github.com/<org>/<repo>/discussions
#     about: Ask or discuss with us, we're happy to help 🙋
